version: '3'

services:
  es:
   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
   restart: always
   environment:
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   volumes:
     - data:/usr/share/elasticsearch/data

  app:
   build: .
   restart: always
   ports:
      - "8000:8000"
   depends_on:
    - es
   command: python manage.py runserver 0.0.0.0:8000

volumes:
  data:
    driver_opts:
        type: none
        device: /srv/ddd/data
        o: bind
    driver: local