version: '3'

services:
  redis:
    image: redis

  app:
   build: .
   restart: always
   ports:
      - "8000:8000"
   depends_on:
    - redis
   command: python manage.py runserver 0.0.0.0:8000


volumes:
  data:
    driver_opts:
        type: none
        device: /srv/ddd/data
        o: bind
    driver: local
