version: '3'

services:
  es:
   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
   restart: always
   environment:
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   volumes:
     - data:/usr/share/elasticsearch/data
     - /srv/ddd/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  app:
   build: .
   restart: always
   ports:
      - "8000:8000"
   depends_on:
    - es
   command: python manage.py runserver 0.0.0.0:8000

  frp:
    build: /srv/frp/
    restart: always
    ports:
      - "1080:80"
      - "6000:6000"
      - "7000:7000"
      - "7500:7500"
    volumes:
      - /etc/frp/frps.ini:/conf/frps.ini
    command: frps -c /conf/frps.ini

volumes:
  data:
    driver_opts:
        type: none
        device: /srv/ddd/data
        o: bind
    driver: local